providers = ['node']

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NIXPACKS_NODE_VERSION = '24'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'

[phases.setup]
nixPkgs = [
    'nodejs_24'
]
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = 'cf93ceb06388f5714302b702cccf2c77f6064442'

[phases.install]
dependsOn = ['setup']
cmds = ['corepack enable pnpm', 'pnpm install --no-prod']
cacheDirectories = ['/root/.local/share/pnpm/store', 'node_modules']
paths = ['/app/node_modules/.bin']

[phases.build]
dependsOn = ['install']
cmds = ['pnpm run build:server']
cacheDirectories = ['node_modules/.cache']

[start]
cmd = 'pnpm run start:server'